from tkinter import *
root=Tk()
root.geometry("600x600")
def myfunc():
    Label(root,text="Saving....").pack()
mymenubar=Menu(root)
m1=Menu(mymenubar,tearoff=0)
m1.add_command(label="Save",command=myfunc)
m1.add_seperator()
m1.add_command(label="Exit",command=quit)
mymenubar.add_cascade(label="File",menu=m1)
m2=Menu(mymenubar,tearoff=0)
m2.add_command(label="Find",command=myfunc)
m2.add_seperator()
m2.add_command(label="Exit",command=quit)
mymenubar.add_cascade(label="Edit",menu=m2)
root.config(menu=mymenubar)
root.mainloop()